pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/refka-jebali/calculatriceJenkins.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t calculatrice-app .'
            }
        }

        stage('Deploy to Test Environment') {
            steps {
                // Supprimer l’ancien conteneur s’il existe
                sh 'docker rm -f calculatrice-test || true'
                // Lancer en test
                sh 'docker run -d -p 3000:3000 --name calculatrice-test calculatrice-app'
                // Attendre un peu que l’app démarre
                sh 'sleep 5'
            }
        }

        stage('Run Selenium Tests') {
            steps {
                sh 'node test_calculatrice.js'
            }
        }

        stage('Deploy to Production (Simulated)') {
            when {
                expression { currentBuild.currentResult == 'SUCCESS' }
            }
            steps {
                sh 'docker rm -f calculatrice-prod || true'
                sh 'docker run -d -p 4000:3000 --name calculatrice-prod calculatrice-app'
            }
        }
    }
}
